### ISSUE TITLE
Credentials exposed

### ISSUE THREAD

**Issue by mondaysunrise** [poppaul95/express-mongo-graphql-boilerplate#3]
https://github.com/poppaul95/express-mongo-graphql-boilerplate/blob/7ea6abda434dfa2a9ebba22739d675dd7f99a83f/src/awsConfig.json#L3

Hi there,

please remove your exposed credentials from your Git repository commit history, change them and externalize.

Cheers,

**Comment by poppaul95** [comment]
Fixed, thanks

**Comment by mondaysunrise** [comment]
Git saves all code history, so you might want to reupload a clean version and deactivate that token: https://github.com/poppaul95/express-mongo-graphql-boilerplate/blob/7ea6abda434dfa2a9ebba22739d675dd7f99a83f/src/awsConfig.json#L3
